name: "Deploy Now: Execute Build"

on:
  workflow_call:
    inputs:
      site-url:
        required: true
        type: string
      branch-id:
        required: true
        type: string

env:
  DEPLOYMENT_FOLDER: ./

jobs:
  build-project:
    name: Build and Deploy Gescon
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Render templates
        uses: ionos-deploy-now/template-renderer-action@v2
        id: template
        with:
          input-directory: .deploy-now/gescon
          output-directory: ${{ env.DEPLOYMENT_FOLDER }}
          intermediate-data-file: ${{ env.DEPLOYMENT_FOLDER }}/.template-renderer-data

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, intl
        env:
          APP_ENV: Production
          APP_URL: ${{ inputs.site-url }}
          DB_DATABASE: dbs12347171
          DB_HOST: db5014863092.hosting-data.io
          DB_PASSWORD: dbPasse21!
          DB_PORT: 3306
          DB_USERNAME: dbu5573703

      - name: Setup Composer
        run: composer install --no-interaction --no-dev --optimize-autoloader

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: v16.x

      - name: Build Node.js assets
        run: |
          npm install --global yarn
          yarn install --frozen-lockfile 

      - name: Build PHP assets
        run: |
          php artisan key:generate --force -n
          php artisan config:clear
          php artisan config:clear
          php artisan cache:clear
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache

      - name: Store deployment content
        uses: ionos-deploy-now/artifact-action@v1
        with:
          api-key: ${{ secrets.IONOS_API_KEY }}
          service-host: api-us.ionos.space
          project-id: 645d34d5-079a-43a7-9fd2-f8ac07f49f0f
          branch-id: ${{ inputs.branch-id }}
          version: ${{ github.sha }}
          folder: ${{ env.DEPLOYMENT_FOLDER }}
          config-file: .deploy-now/gescon/config.yaml
          action: upload
